### ISSUE TITLE
Map không khớp ở các đoạn dốc 

### ISSUE THREAD

**Issue by saruno** [pipogame/rambo2017#1]
Trên một số đoạn dốc vẫn xảy ra tình trạng không khớp giữa các Tiled với nhau. Minh họa như ảnh chụp màn hình phía dưới
![2017-02-08-21-45-54](https://cloud.githubusercontent.com/assets/4100178/22743498/ee197406-ee4c-11e6-8d10-4e876f57772e.png)
![2017-02-08-21-45-54](https://cloud.githubusercontent.com/assets/4100178/22743507/f5cb22ee-ee4c-11e6-9c7c-0d59ac059417.png)

**Comment by saruno** [comment]
Có đoạn sinh item còn ở vị trí ko biết ăn kiểu gì nữa 
![2017-02-08-21-48-08](https://cloud.githubusercontent.com/assets/4100178/22743652/5e28819c-ee4d-11e6-8e17-9a73e54c8846.png)

**Comment by raphlee** [comment]
Về vị trí của các item cũ, em chưa chỉnh gì ạ, em chỉ mới thêm item_health vào 1 số map ban đầu :v

**Comment by raphlee** [comment]
Em fix lại tiledMap r anh =))
