### ISSUE TITLE
Map ở vị trí hơi thấp so với màn hình

### ISSUE THREAD

**Issue by saruno** [pipogame/rambo2017#2]
Phần đất thấp nhất ở map quá sát với đáy màn hình. Đẩy map lên cao 1 chút, tạo cảm giác dễ chịu hơn cho người chơi. Nhân vật lúc sinh ra nên ở khoảng giữa màn hình để tránh bị nút điều khiển che mất
![2017-02-08-22-25-36](https://cloud.githubusercontent.com/assets/4100178/22743794/e40c3fba-ee4d-11e6-9409-ad2f4d970bf3.png)

**Comment by ThuanDoVan** [comment]
#fix
Sửa tỷ lệ nâng map cấu hình trong file Global.h, giá trị: Y_INCREMENT_RATIO

**Comment by saruno** [comment]
Anh chỉnh nút joystick ko bị khuất nhưng khi vào game lại bị khuất mất 1 phần joystick. Máy anh độ phân giải fullhd 1920x1080 

![2017-02-10-21-21-49](https://cloud.githubusercontent.com/assets/4100178/22829941/5c8368bc-efd7-11e6-8669-f4bffdc65c86.png)

![2017-02-10-21-22-02](https://cloud.githubusercontent.com/assets/4100178/22829955/68deee88-efd7-11e6-86b6-ae17205c8bd0.png)

**Comment by raphlee** [comment]
Fix joystick's position: setAnchorPoint in addXXX method (Hud.cpp)
