### ISSUE TITLE
Sửa lại hành động của quái chạy 

### ISSUE THREAD

**Issue by saruno** [pipogame/rambo2017#4]
Hành động của quái chạy hiện giờ hơi đơn điệu và dày đặc. Tham khảo game Contra để làm quái chạy hợp lý hơn. (Không chạy ra liên tục mà chạy ra thưa thớt hơn, chạy theo tốp 3 đứa, chạy ngang nhiều hơn, ...)

[https://www.youtube.com/watch?v=2mWZlNOzdv8](url)

**Comment by ThuanDoVan** [comment]
Chạy ngang nhiều hơn là sao anh ? Tăng vận tốc di chuyển ngang của thằng người chạy à anh ?

**Comment by ThuanDoVan** [comment]
#fix
Dùng thêm biến để điều khiển việc sinh quái theo top trong class GameScene
Sắp xếp lại những khu vực sinh quái chạy ở vị trí cao xuống dưới thấp  tránh hiện tượng "thác nước"

**Comment by ThuanDoVan** [comment]
#fix "máy bay bay có va chạm nền đất"
Sử dụng body dạng sensor cho máy bay
