### ISSUE TITLE
Quái bị mắc ở khe map và không thoát được

### ISSUE THREAD

**Issue by saruno** [pipogame/rambo2017#6]
Quái bị mắc kẹt ở khe ko xuống dưới được. Có thể khắc phục bằng cách cho body của quái là hình tròn.

![2017-02-10-21-26-43](https://cloud.githubusercontent.com/assets/4100178/22830162/0ed48adc-efd8-11e6-8561-c52500744f7b.png)

**Comment by raphlee** [comment]
#Fix: setFriction = 0 in GenDEnemy() method (GameScene.cpp)
